# Copyright (c) The OpenTofu Authors
# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2024 HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
changelog:
  exclude:
    labels:
      - release
      - dependencies
  categories:
    - title: New Features
      labels:
        - feature
        - enhancement
    - title: Bugs Fixed
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'
